### ISSUE TITLE
Type errors in componentMemberOrderRule.ts

### ISSUE THREAD

**Issue by natemoo-re** [natemoo-re/tslint-stencil#11]
@patricksevat, I missed this on #6, but ran into some Typescript errors when trying to cut a new release. I'll have a fix shortly—just wanted to be sure it's tracked.

In [`componentMemberOrderRule.ts#L227`](https://github.com/natemoo-re/tslint-stencil/blob/master/src/componentMemberOrderRule.ts#L227), `groups` is typed as `ComponentMetadata[]`, but the block below seems to treat `groups` as `string[]`.

**Comment by patricksevat** [comment]
@natemoo-re thanks for letting me know. I saw that, was planning to create a new PR when I get home from work, but leave it to you now. But do let me know if you get stuck, am glad to help
