### ISSUE TITLE
`hostData()` method has been removed

### ISSUE THREAD

**Issue by chrisweight** [natemoo-re/tslint-stencil#13]
This means `stencil-method-order` is no longer required and can be removed

**Comment by chrisweight** [comment]
Reference: https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#hostdata

**Comment by natemoo-re** [comment]
Thanks! Closed via [commit df8ae59](https://github.com/natemoo-re/tslint-stencil/commit/df8ae598f1bb03f545f99dd4117b351d6a2623d6)
