### ISSUE TITLE
components-per-file error

### ISSUE THREAD

**Issue by vogloblinsky** [natemoo-re/tslint-stencil#3]
Node.js : 8.12.0
npm : 6.5.0
Stencil project.

I just installed your rule, and got this error after running the default npm script provided by Stencil CLI :

`
"lint": "tslint -c tslint.json 'src/**/*.tsx' 'src/**/*.ts'"
`

`
Could not find implementations for the following rules specified in the configuration:
    components-per-file
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
`

**Comment by gagaXD** [comment]
I'm having the same issue on my project. Anyone found a solution ?

**Comment by natemoo-re** [comment]
Better late than never? This should be fixed in the upcoming `v1.0.1`
